#pragma once

#include <ncurses.h>

typedef enum{

WFR_BLACK = COLOR_BLACK,
WFR_WHITE = COLOR_WHITE,
WFR_BLUE = COLOR_BLUE,
WFR_RED = COLOR_RED,
WFR_TELLOW = COLOR_YELLOW,
WFR_MAGENTA = COLOR_MAGENTA,
WFR_CYAN = COLOR_CYAN,
WFR_GREEN = COLOR_GREEN

} wfrColor;
